version: 0.1
            
phases:

  install: 
    commands:

  pre_build: 
    commands:
   
    # Make the required folder with proper name for this service
    - mkdir -p $RRP_HOME/rfid-alert-service

    # copy all files to folder with the proper name, but leave originals here for use later in docker image step
    - cp -r * $RRP_HOME/rfid-alert-service

    # Run all the unit tests
    - cd $RRP_HOME/rfid-alert-service; go test -cover -v $(go list ./... | grep -v /vendor/)
  build:
    commands:
    # Build our application from the proper folder structure and place executable in current directory for building the docker image
    - cd $RRP_HOME/rfid-alert-service; CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o ./rfid-alert-service .
    - cp $RRP_HOME/rfid-alert-service/rfid-alert-service .

artifacts:
  files: 
  - Dockerfile.release
  - rfid-alert-service