# Apache v2 license
#  Copyright (C) <2019> Intel Corporation
#
#  SPDX-License-Identifier: Apache-2.0
#


version: '3.4'

networks:
  main-net:

services:  

  Alert:
    image: rsp/alert-service:dev
    user: "2000:2000"
    networks:
      - main-net
    extra_hosts:
      - "edgex-core-data:172.17.0.1"
      - "edgex-support-logging:172.17.0.1"
      - "edgex-core-consul:172.17.0.1"
      - "edgex-core-command:172.17.0.1"
      - "edgex-support-notifications:172.17.0.1"
    healthcheck:
      test: curl --fail -s http://localhost:8080/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
    logging:
      options: {max-file: '5', max-size: 100m}
    environment:       
      loggingLevel: "info"
      telemetryEndpoint: ""
      telemetryDataStoreName: "telemetry"
      responseLimit: 10000      
      port: "8080"      
      cloudConnectorURL: "http://cloud-connector:8080"
      mappingSkuURL : "http://product-data:8080"
      watchdogSeconds: 120
      serviceName: "Alert service"
      maxMissedHeartbeats: 3
      notificationChanSize: 100
      cloudConnectorEndpoint: "/callwebhook"
      heartbeatEndpoint: "/heartbeat"
      mappingSkuEndpoint: "/skus"
      alertDestination: ""
      heartbeatDestination: ""
      batchSizeMax: 50
      sendNotWhitelistedAlert: "false"
      alertDestinationAuthEndpoint: ""
      alertDestinationAuthType: ""
      alertDestinationClientID: ""
      alertDestinationClientSecret: ""
