version: "3"
networks:
  main:
services:
  #CSSDK Broker
  contextbroker:
    image: "280211473891.dkr.ecr.us-west-2.amazonaws.com/context/context-broker:v0.14.0"
    logging:
      driver: "none"
    networks:
      main:
        aliases:
          - broker
    environment:
      MONGODB_HOST: "mongo"
      MONGODB_PORT: "27017"
    ports:
      - 8888:8888
    depends_on:
      - rrpmongo
  #rfid-data microservice, listens to RRS GW and puts data on to ContextSensingBus
  rfid-data:
    image: "280211473891.dkr.ecr.us-west-2.amazonaws.com/context/rrs-rfid-provider:v0.9.4"
    command: ["--server", "contextbroker:8888", "--gateway", "rrptavern.ch.intel.com:1883"]
    networks:
      main:
    logging:
      options:
        max-size: "1000m"
        max-file: "5"
    depends_on:
      - contextbroker
    restart: always
  #Mongodb
  rrpmongo:
    image: mongo:3.2
    networks:
      main:
        aliases:
          - mongo
    volumes:
      - ./data:/data/db
    ports:
      - 27018:27017
  #rfid alert service
  # rfid-alert:
  #   build: ./
  #   ports:
  #     - 8084:8080
  #   networks:
  #     main:
  #   depends_on:
  #     - contextbroker
  #   restart: always
