consumes:
  - application/json
produces:
  - application/json
schemes:
  - http
  - https
swagger: '2.0'
info:
  description: |-
    RFID Alert service provides the capabilities to monitor Intel® RSP Controller status and send alerts. Intel® RSP Controller status is updated periodically based on events sent through Heartbeat listener from EdgeX Core Data and alerts are generated when heartbeats are missed. Also, alert events are processed and posted to the REST endpoint specified.

    __Configuration Values__
    <blockquote>RFID Alert service configuration is split between values set in a configuration file and those set as environment values in compose file. The configuration file is expected to be contained in a docker secret for production deployments, but can be on a docker volume for validation and development.
    <blockquote><b>Configuration file values</b>
    <blockquote>•<b> serviceName</b> - Runtime name of the service.</blockquote>
    <blockquote>•<b> loggingLevel</b> - Logging level to use: "info" (default) or "debug" (verbose).</blockquote>
    <blockquote>•<b> notificationChanSize</b> - Channel size of a go channel named as notificationChan.</blockquote>
    <blockquote>•<b> port</b> - Port to run the service's HTTP Server on.</blockquote>
    <blockquote>•<b> contextSensing</b> - Host and port number for the Context Broker.</blockquote>
    <blockquote>•<b> watchdogSeconds</b> - Time interval set to check the status of registered gateways</blockquote>
    <blockquote>•<b> maxMissedHeartbeats</b> - Maximum heart beats that can be missed before the gateway gets deregistered.</blockquote>
    <blockquote>•<b> cloudConnectorURL</b> - URL for Cloud-connector service.</blockquote>
    <blockquote>•<b> cloudConnectorEndpoint</b> - Endpoint for Cloud-connector service.</blockquote>
    <blockquote>•<b> Destination</b> - Endpoint URL for Cloud-connector to send notificaiton to.</blockquote>
    <blockquote>•<b> telemetryEndpoint</b> - URL of the telemetry service receiving the metrics from the service.</blockquote>
    <blockquote>•<b> telemetryDataStoreName</b> - Name of the data store in the telemetry service to store the metrics.</blockquote>
    </blockquote>

    <pre><b>Example configuration file json
    &#9{
    &#9&#9"serviceName": "RRP - RFID Alert service",
    &#9&#9"loggingLevel": "debug",
    &#9&#9"notificationChanSize": 100,
    &#9&#9"port": "8080",
    &#9&#9"contextSensing": "127.0.0.1:8888",
    &#9&#9"watchdogSeconds": 1,
    &#9&#9"maxMissedHeartbeats": 3,
    &#9&#9"cloudConnectorURL": "http://127.0.0.1:8081",
    &#9&#9"cloudConnectorEndpoint": "/aws/invoke",
    &#9&#9"Destination": "https://test.com/call",
    &#9&#9"secureMode": false,
    &#9&#9"skipCertVerify": false,
    &#9&#9"telemetryEndpoint": "http://166.130.9.122:8000",
    &#9&#9"telemetryDataStoreName" : "Store105",
    &#9}
    </b></pre>
    <pre><b>Example environment variables in compose file
    &#9cloudConnectorURL: "https://cloudconnector:5001",
    &#9runtimeConfigPath: "/data/configs/rfid-alert.json"
    &#9contextSenisng: "127.0.0.1:8888",
    </b></pre>
    </blockquote>

    __Secrets__
    The following values/files are passed to the service via Docker Secrets
    <blockquote>
    <blockquote>•<b> configuration.json</b> - Configuration file referenced above</blockquote>
    </blockquote>

    __Known services this service depends on:__
    ○ Context Sensing
    ○ Cloud-connector

    __Known services that depend upon this service:__
    ○ None
  title: RFID Alert Service API
  contact:
    name: RRP
    email: rrp@intel.com
  version: 0.0.1
host: 'rfid-alert-service:8080'
basePath: /
paths:
  /:
    get:
      description: 'Endpoint that is used to determine if the application is ready to take web requests, i.e is healthy'
      consumes:
        - application/json
      produces:
        - application/json
      schemes:
        - http
      tags:
        - default
      summary: Healthcheck Endpoint
      operationId: Healthcheck
      responses:
        '200':
          description: OK
  /rfid-alert/alertmessage:
    post:
      description: |-
        Alert message for events should be in request body payload in JSON format.<br><br>

        Example AlertMessage Input:
        ```
        {
        &#9"application":"Inventory-service",
        &#9"value": {
        &#9&#9"sent_on":1531522680000,
        &#9&#9"alert_description":"Deletion of system database tag collection is complete",
        &#9&#9"severity":"critical",
        &#9&#9"optional":"event alert related data"
        &#9}
        }
        ```


        + application  - the application sending the alert message
        + sent_on  - the time that alert message is sent in millisecond epoch
        + alert_description  - the detailed message for the alert
        + severity  - the severity of the alert
        + optional  - contains any alert related data or evidence and can be omitted



        Response will be either Ok or error messages when posting to cloud connector fails.
      consumes:
        - application/json
      produces:
        - application/json
      schemes:
        - http
      summary: Send alert message for events and post the message to the cloud connector
      operationId: sendAlertMessage
      responses:
        '200':
          $ref: '#/responses/statusOk'
        '400':
          $ref: '#/responses/schemaValidation'
        '500':
          $ref: '#/responses/internalError'
        '503':
          $ref: '#/responses/serviceUnavailable'
definitions:
  AdvanceShippingNotice:
    description: AdvanceShippingNotice is the model containing advance shipping item epcs
    type: object
    properties:
      asnId:
        type: string
        x-go-name: AsnID
      eventTime:
        type: string
        x-go-name: EventTime
      items:
        type: array
        items:
          $ref: '#/definitions/AdvanceShippingNoticeItem'
        x-go-name: Items
      siteId:
        type: string
        x-go-name: SiteID
    x-go-package: github.impcloud.net/RSP-Inventory-Suite/rfid-alert-service/app/models
  AdvanceShippingNoticeItem:
    type: object
    properties:
      itemEpcs:
        type: array
        items:
          type: string
        x-go-name: Epcs
      itemGtin:
        type: string
        x-go-name: ProductID
      itemId:
        type: string
        x-go-name: Sku
    x-go-package: github.impcloud.net/RSP-Inventory-Suite/rfid-alert-service/app/models
  ErrReport:
    description: ErrReport is used to wrap schema validation errors int json object
    type: object
    properties:
      description:
        type: string
        x-go-name: Description
      errortype:
        type: string
        x-go-name: ErrorType
      field:
        type: string
        x-go-name: Field
      value:
        type: object
        x-go-name: Value
    x-go-package: github.impcloud.net/RSP-Inventory-Suite/rfid-alert-service/app/routes/schemas
  ProdData:
    description: ProdData represents the product data schema in the database
    type: object
    properties:
      productList:
        type: array
        items:
          $ref: '#/definitions/ProductMetadata'
        x-go-name: ProductList
    x-go-package: github.impcloud.net/RSP-Inventory-Suite/rfid-alert-service/app/models
  ProductID:
    description: ProductID represents the ProductID object
    type: object
    properties:
      productId:
        type: string
        x-go-name: ProductID
    x-go-package: github.impcloud.net/RSP-Inventory-Suite/rfid-alert-service/app/models
  ProductMetadata:
    description: ProductMetadata represents the ProductList schema attribute in the database
    type: object
    properties:
      productId:
        type: string
        x-go-name: ProductID
    x-go-package: github.impcloud.net/RSP-Inventory-Suite/rfid-alert-service/app/models
  SkuMappingResponse:
    description: |-
      SkuMappingResponse is the model of the response from the mapping sku service
      with the selection of only the product id
    type: object
    properties:
      results:
        type: array
        items:
          $ref: '#/definitions/ProdData'
        x-go-name: ProdData
    x-go-package: github.impcloud.net/RSP-Inventory-Suite/rfid-alert-service/app/models
responses:
  internalError:
    description: JSONError is the response for errors that occur within the API.
    headers:
      error:
        type: string
  schemaValidation:
    description: ErrorList provides a collection of errors for processing
    schema:
      type: array
      items:
        $ref: '#/definitions/ErrReport'
  serviceUnavailable:
    description: serviceUnavailable
  statusOk:
    description: statusOk
